export default [
{
    id:1,
    postDn:'2025-10-08',
    title:'iOS Developer',
    company:'Amazon',
    type:"Full time",
    experience:"Mid Level",
    location:"Remote",
    skills:["SwiftUI","Uikit","Core Data"],
    job_link:"",
},
{
    id:2,
    postDn:'2025-10-08',
    title:'iOS Developer',
    company:'Amazon',
    type:"Full time",
    experience:"Mid Level",
    location:"Remote",
    skills:["SwiftUI","Uikit","Core Data"],
    job_link:"",
},
{
    id:3,
    postDn:'2025-10-08',
    title:'iOS Developer',
    company:'Amazon',
    type:"Full time",
    experience:"Mid Level",
    location:"Remote",
    skills:["SwiftUI","Uikit","Core Data"],
    job_link:"",
},
{
    id:4,
    postDn:'2025-10-08',
    title:'iOS Developer',
    company:'Amazon',
    type:"Full time",
    experience:"Mid Level",
    location:"Remote",
    skills:["SwiftUI","Uikit","Core Data"],
    job_link:"",
},
]